spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.renewal-percent-threshold=0.85
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.server.enable-self-preservation=true
keycloak.client-secret=qbQnDwahBBE4ohGVEME4vADk52uEM3pJ

spring.cloud.config.override-none=false

keycloak.base-uri=http://localhost:8091/auth/realms/
keycloak.authorization-uri=http://localhost:8091/realms/Donaton/protocol/openid-connect/auth
keycloak.user-info-uri=http://localhost:8091/realms/Donaton/protocol/openid-connect/userinfo
keycloak.token-uri=http://localhost:8091/realms/Donaton/protocol/openid-connect/token
keycloak.logout=http://localhost:8091/realms/Donaton/protocol/openid-connect/logout
keycloak.jwk-set-uri=http://localhost:8091/realms/Donaton/protocol/openid-connect/certs
keycloak.jwk.url=http://localhost:8091/realms/Donaton/protocol/openid-connect/certs

keycloak.client-id=front-client-app
keycloak.scope=profile
keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token