spring.application.name=keycloak
server.port=8080
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

keycloak.base-uri=http://${KEYCLOAK_HOST:localhost}:8080/auth/realms/
keycloak.authorization-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/Donaton/protocol/openid-connect/auth
keycloak.user-info-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/Donaton/protocol/openid-connect/userinfo
keycloak.token-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/Donaton/protocol/openid-connect/token
keycloak.logout=http://${KEYCLOAK_HOST:localhost}:8080/realms/Donaton/protocol/openid-connect/logout
keycloak.jwk-set-uri=http://${KEYCLOAK_HOST:localhost}:8080/realms/Donaton/protocol/openid-connect/certs
keycloak.jwk.url=http://${KEYCLOAK_HOST:localhost}:8080/realms/Donaton/protocol/openid-connect/certs

keycloak.certs-id=${KEYCLOAK_CERTS_ID:r2RN6wtySEg9M_cnH4OoLFUWGn6oDOzxh9DAtJIwpmk}
keycloak.client-id=front-client-app
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:qwerty}
keycloak.scope=profile
keycloak.authorization-grant-type=password
keycloak.authorization-grant-type-refresh=refresh_token

keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin}

logging.level.root=INFO
